version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: pokedex
      PGDATA: /var/lib/postgresql/data/pgdata/
    volumes:
      - "./pg_data:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
  pokedex:
    image: pokedex:0.1
    restart: always
    ports:
      - "8000:8000"
