version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: proreview
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pg_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
