# Generated by Django 4.0.2 on 2022-02-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_creature_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex_app.pokedex'),
        ),
    ]
